language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
  - ./travis-tool.sh r_binary_install gridExtra
  - ./travis-tool.sh r_binary_install ggplot2
  - ./travis-tool.sh r_binary_install reshape2
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install Rcpp
  
script: 
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

